default to new perf event handling API, revert if needed
`perf` added an additional parameter to event handlers, perf_sample_dict,
in Linux 4.14 (commit a641860550f05a4b8889dca61aab73c84b2d5e16), which
altered the event handler API in a binary-incompatible way.
Using the new API on a system which does not support it results in an
exception like:
```
  TypeError: event__handler() takes exactly 11 arguments (10 given)
```
Here, we catch all exceptions, and if one seems to match the above exception,
we start all over, attempting to revert to the older perf event handler API.

Signed-off-by: Paul A. Clarke <pc@us.ibm.com>